language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  - OPAMERRLOGLEN=0
  - PACKAGE=capnp
  matrix:
  - DISTRO=debian-9 OCAML_VERSION=4.04
  - DISTRO=debian-9 OCAML_VERSION=4.06
  - DISTRO=debian-9 OCAML_VERSION=4.07
