[package]
name = "stateright-test"
version = "0.1.0"
authors = ["Cjen1 <cjj39@cam.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7"
stateright = "0.28"
